"""empty message

Revision ID: 6b6be71ce7c6
Revises: 7bd6f42b678c
Create Date: 2021-09-07 11:00:35.507761

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '6b6be71ce7c6'
down_revision = '7bd6f42b678c'
branch_labels = None
depends_on = None

cur_time = datetime.now()
cur_time = str(cur_time.date())

# op.execute('UPDATE todos SET completed = False WHERE completed is NULL;')
#     op.execute('ALTER TABLE todos ALTER COLUMN completed TYPE BOOLEAN USING completed::boolean;')
#     op.alter_column('todos', 'completed', nullable=False)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('venue', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.execute(f"UPDATE artist SET created_on = to_timestamp('2020-09-01 9:30:20', 'YYYY-MM-DD HH:MI:SS')")
    op.execute(f"UPDATE venue SET created_on = to_timestamp('2020-09-01 9:30:20', 'YYYY-MM-DD HH:MI:SS')")
    # op.execute(f"UPDATE venue SET created_on = to_timestamp({datetime.datetime(2020,10,1)}) WHERE created_on is 1970-01-01 09:33:25")
    op.alter_column('artist', 'created_on', nullable=False)
    op.alter_column('venue', 'created_on', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'created_on')
    op.drop_column('artist', 'created_on')
    # ### end Alembic commands ###
