"""empty message

Revision ID: 7bd6f42b678c
Revises: 3e47115423e5
Create Date: 2021-09-06 13:53:41.262288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bd6f42b678c'
down_revision = '3e47115423e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('venue_genres_venue_id_fkey', 'venue_genres', type_='foreignkey')
    op.create_foreign_key(None, 'venue_genres', 'venue', ['venue_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue_genres', type_='foreignkey')
    op.create_foreign_key('venue_genres_venue_id_fkey', 'venue_genres', 'venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###
